# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailkube" do
  version "1.1.3"

  on_macos do
    on_arm do
      sha256 "9d0baff112d68c9e13a8387822862e6120a599cac2db46a751edce7a143225c0"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b863afa2233e168b3e2a54c4bbe0c75dade39e03c06e33875c38e66228db2fd"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6c058d07fe6a272b496f6dad11b079841944be08e6b00ea75c915030ad66bf1"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mailkube"
  desc "Send mail, manage scheduled sends, and receive webhooks from your terminal."
  homepage "https://docs.mailkube.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailkube"
  bash_completion "completions/mailkube.bash"
  fish_completion "completions/mailkube.fish"
  zsh_completion "completions/mailkube.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailkube"]
    end
  end

  # No zap stanza required

end
