# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailkube" do
  version "1.1.5"

  on_macos do
    on_arm do
      sha256 "a2576d1dab506938534aeb4816426436e0c42b24890373f564f9a584458628f5"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6bc8828dbc119a4c53d7838a2b707ef7e95e721e5446d7ccd3dc048424315c2f"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "638fa31fa7adddab98fb0e80fccaf9e4887687bcc3490d0071886dcabb2423d5"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mailkube"
  desc "Send mail, manage scheduled sends, and receive webhooks from your terminal."
  homepage "https://docs.mailkube.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailkube"
  bash_completion "completions/mailkube.bash"
  fish_completion "completions/mailkube.fish"
  zsh_completion "completions/mailkube.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailkube"]
    end
  end

  # No zap stanza required

end
