# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailkube" do
  on_macos do
    on_intel do
      odie "No Intel build of mailkube exists. If this is Apple Silicon hardware, you are likely running an x86_64 Homebrew (often /usr/local, installed under Rosetta) instead of the native one at /opt/homebrew - check `brew --prefix` and reinstall via the native prefix. Otherwise, on a genuine Intel Mac, install with: go install github.com/mailkube/mailkube-cli/cmd/mailkube@latest"
    end
  end

  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "a7de73cf0e0d3612e970833d1ed9b613fefac94aa69d034b28c80660922ab070"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b7bed3b8cfe83d46a3bbe30c3a34255e4f67835b31a4e43ae101166e5d4104b2"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7855f701408ad034d83a3b6049743a03130fd1dd8aeff5409815351324887e96"
      url "https://github.com/mailkube/mailkube-cli/releases/download/v#{version}/mailkube_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mailkube"
  desc "Send mail, manage scheduled sends, and receive webhooks from your terminal."
  homepage "https://docs.mailkube.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailkube"
  bash_completion "completions/mailkube.bash"
  fish_completion "completions/mailkube.fish"
  zsh_completion "completions/mailkube.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailkube"]
    end
  end

  # No zap stanza required
end
